server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: customer-management
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**, 
        - id: restaurant-management
          uri: http://localhost:8083
          predicates:
            - Path=/restaurants/**, 
        - id: rider-management
          uri: http://localhost:8084
          predicates:
            - Path=/riders/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: customer-management
          uri: http://customerManagement:8080
          predicates:
            - Path=/orders/**, 
        - id: restaurant-management
          uri: http://restaurantManagement:8080
          predicates:
            - Path=/restaurants/**, 
        - id: rider-management
          uri: http://riderManagement:8080
          predicates:
            - Path=/riders/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
